ARG NVF_BASE_IMAGE_CLIENT
FROM ${NVF_BASE_IMAGE_CLIENT}

ENV SHELL=/bin/bash

ARG NVF_REPO
ARG NVF_VERSION
ENV NVF_BRANCH=${NVF_VERSION}

RUN apt-get update && apt-get install -y \
	git \
	iputils-ping \
	lsof \
	netcat \
	vim

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install --upgrade jupyterlab

WORKDIR /opt
RUN git clone https://github.com/${NVF_REPO}/NVFlare.git --branch ${NVF_BRANCH} --single-branch NVFlare

WORKDIR /opt/NVFlare
RUN pip install -U pip
RUN pip install -e .

WORKDIR /workspace
