ARG NVF_BASE_IMAGE_DASHBOARD=python:3.11.15-alpine3.24
ARG NVF_REPO
ARG NVF_VERSION

FROM ${NVF_BASE_IMAGE_DASHBOARD}

ARG NVF_REPO
ARG NVF_VERSION

ENV SHELL=/bin/bash

RUN apk update && \
  apk add bash && \
  apk add git && \
  apk add vim && \
  apk add curl && \
  apk add gcc python3-dev musl-dev linux-headers && \
  apk add zip

RUN pip install -U pip
RUN pip install -U setuptools

WORKDIR /workspace
RUN git clone https://github.com/${NVF_REPO}/NVFlare.git --branch ${NVF_VERSION} --single-branch NVFlare

WORKDIR /workspace/NVFlare
RUN pip install -e .

WORKDIR /workspace

#
# waitress
#
RUN pip install -U waitress

COPY ./dashboard/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./dashboard/run.sh /run.sh
RUN chmod +x /run.sh

COPY ./dashboard/app /app

ENV PYTHONPATH=/app

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]

CMD ["/run.sh"]
