ARG NVF_BASE_IMAGE_SERVER=tensorflow/tensorflow:2.17.0-jupyter
FROM ${NVF_BASE_IMAGE_SERVER}

ENV SHELL=/bin/bash

ARG NVF_REPO
ARG NVF_VERSION
ENV NVF_BRANCH=${NVF_VERSION}

RUN apt-get update && apt-get install -y \
	git \
	iputils-ping \
	lsof \
	netcat \
	vim \
	jq

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

WORKDIR /workspace
RUN git clone https://github.com/${NVF_REPO}/NVFlare.git --branch ${NVF_BRANCH} --single-branch NVFlare

WORKDIR /workspace/NVFlare
# blinker 1.4 is preinstalled via distutils in the base image and cannot be
# uninstalled by pip. Install a newer blinker first (ignoring the distutils
# copy) so the editable install below doesn't try to uninstall it. Keeping
# --ignore-installed off the main transaction lets pip preserve the
# TF-2.17-compatible numpy (<2.0) instead of pulling in an incompatible 2.x.
RUN pip install --ignore-installed blinker
RUN pip install -e .

WORKDIR /workspace
